on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            filename: groupme-download-linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            filename: groupme-download-win.exe
          - os: macos-latest
            target: aarch64-apple-darwin
            filename: groupme-download-mac
    steps:
      - uses: actions/checkout@v4
      - name: cargo build
        shell: bash
        run: |
          rustup update
          cargo build --release --target ${{ matrix.target }}
          cp "target/${{ matrix.target }}/release/groupme-download-rust" "${{ matrix.filename }}"
      - uses: actions/upload-artifact@v4
        with:
          name: "artifact_${{ matrix.os }}"
          path: ${{ matrix.filename }}
  release:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: artifact_*
          merge-multiple: true
      - name: create release and upload artifacts
        run: gh release create ${{ github.ref_name }} ./artifacts/* -p
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
