on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: cargo build
        shell: bash
        run: |
          rustup update
          cargo build --release --target ${{ matrix.target }}
          cp "target/${{ matrix.target }}/release/groupme-download-rust" "artifacts/${{ matrix.os }}"
      - uses: actions/upload-artifact@v4
        with:
          name: "artifact_${{ matrix.os }}"
          path: artifacts/
  release:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: artifact_*
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
